[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=c++11
    -std=c++14

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -I include
    -isystem .pio/libdeps/esp32-s3-devkitc-1/LovyanGFX/src
    -std=gnu++17

build_src_flags =
    -Wall
    -Wextra
    -Wpedantic
    -Wshadow
    -Wconversion

lib_ldf_mode = deep+

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.12
